### PR TITLE
Libax25

### PR DESCRIPTION
**Pull request by we7u**
Fixing another compiler warning (variable set but not used) that shows up on the minimal Ubuntu-14.04 build when libax25 is not present. This is part of the fixes for issue #24.

### CODE REVIEW

**Comment by tvrusso** [comment]
On second thought, this PR seems to be a combination of an alternate fix for closed PR #86 and a separate issue, but the fix of the null string has a merge commit log instead of a descriptive one.

I can fix it up manually and do the merge myself.  Will keep this PR open for a bit while I do that.

**Comment by tvrusso** [comment]
I rebased and cleaned up the branch myself and pushed.

**Comment by tvrusso** [comment]
Actually, the method chosen to "do something" here introduces a new "tautological compare" warning from Clang, since "button_ok == button_ok" is always true.  I'll fix that up.

**Comment by tvrusso** [comment]
I changed it to "button_ok == button_cancel" (which will always be false at run time, but the compiler can't tell), so now it should get neither the unused variable NOR the tautological compare warning.

**Comment by we7u** [comment]
Tom: I'm uncomfortable at this point with _any_ rebasing, so I'm glad you took care of it. Will ask question on the -dev list somewhat related to this.

**Pull request closed without merging**
