### PR TITLE
Add IPv6 UDP server support

### PR DESCRIPTION
**Pull request by godfreja**
Adds UDP server IPv6 support and update xastir_udp_client to support IPv6.

The server will open a separate socket for IPv4 and IPv6.

When adding IPv6 support you get multiple addresses to try from a domain name resolutions. For the UDP client try each address, waiting for up to 10 seconds for a response before moving on to the next address. (The addresses come back in the order recommended.)

### CODE REVIEW

**Comment by tvrusso** [comment]
I haven't time to test this out just yet, and may not for a couple of weeks.  I see you are still making commits to this PR.  Is it ready, or still a work in progress?

My testing will be limited to making sure this doesn't break the IPv4 UDP server, which I do on occasion use.  I will be unable to test the IPv6 server.  @we7u , will you be able to do any testing of this code in the coming weeks?

**Comment by godfreja** [comment]
No worries on timeframe. I don't think anyone is itching for this functionality, I'm just adding IPv6 support in as a side project.

The PR is ready. With the last commit I had just realized I had left in a memory leak. Not really critical  since the program was on the way to exiting, but I like to be thorough. Since this hadn't been merged yet I decided to push a fix.

**Comment by we7u** [comment]
On Mon, 4 Dec 2017, Tom Russo wrote:

> I haven't time to test this out just yet, and may not for a couple of weeks.  I see you are still making commits to this PR.  Is it ready, or still a work in progress?
>
> My testing will be limited to making sure this doesn't break the IPv4 UDP server, which I do on occasion use.  I will be unable to test the IPv6 server.  @we7u , will you be able to do any testing of this code in the coming weeks?

Not likely. I'm working on a side project hot and heavy at lunchtime and after work, should be still busy on it through most of January and maybe February. I'm not even all that engaged in answering Xastir list email at the moment.

I think I'd have to enable IPv6 on my Comcast modem, then see if my router (or the newer one I want to replace it with) can do IPv6 before I could even test. Means I'd break the home network while initially experimenting/replacing things and the citizenry there might run me out with pitchforks.

-- 
Curt, WE7U.        http://we7u.wetnet.net
U.S. Weather Alerts:  Firenet.aprs2.net, port 14580, filter "t/n e/WE7U-WX"
Coordinate Converter (Android): http://www.sarguydigital.com

**Comment by we7u** [comment]
On Mon, 4 Dec 2017, Jason Godfrey wrote:

> No worries on timeframe. I don't think anyone is itching for this functionality, I'm just adding IPv6 support in as a side project.
>
> The PR is ready. With the last commit I had just realized I had left in a memory leak. Not really critical  since the program was on the way to exiting, but I like to be thorough. Since this hadn't been merged yet I decided to push a fix.

Olivier, n7tap, may be able to help test it more easily, as he's had IPv6 running from home for a few years. Another Xastir developer. I can ask him next time I see him walking down the hallway here.

-- 
Curt, WE7U.        http://we7u.wetnet.net
   "Lotto:  A tax on people who are bad at math." - unknown
"Windows:  Microsoft's tax on computer illiterates." - WE7U.
Coordinate Converter (Android): http://www.sarguydigital.com

**Comment by we7u** [comment]
On Mon, 4 Dec 2017, Curt, WE7U wrote:

> Olivier, n7tap, may be able to help test it more easily, as he's had IPv6 
> running from home for a few years. Another Xastir developer. I can ask him 
> next time I see him walking down the hallway here.

Hah. Caught him on IM. Talked to him in person 30 seconds ago. He's going to give it a shot from his home system.

-- 
Curt, WE7U.        http://we7u.wetnet.net
APRS in Search and Rescue:  http://we7u.wetnet.net/search_and_rescue.html
Coordinate Converter (Android): http://www.sarguydigital.com

**Comment by tvrusso** [comment]
Excellent.  If he can comment on this PR confirming it works for him, I'll test the "doesn't break ipv4" aspect (since FreeBSD is the problem child when it comes to IPv6 vs. IPv4) as soon as I can, then merge the PR when we've all signed off on it.

**Comment by K2DLS** [comment]
I am using IPv6 extensively and can test a UDP connection from javAPRSSrvr.  Ping me if needed.  I am definitely looking for IPv6 support in Xastir.

**Pull request merged**
