### PR TITLE
Further rework dialogs to support small screens

### PR DESCRIPTION
**Pull request by we7u**
More fixes for dialogs w/scrollbars. This resizes properly on my system for small screens and large. Results may vary based on window manager selection/settings and font selection. More to do yet as not all dialogs have the new code added.

### CODE REVIEW

**Comment by tvrusso** [comment]
Dude, this branch is totally messed up.  It contains many commits other than the ones you intended.  It looks like you failed to update your fork before doing the work.

**Comment by tvrusso** [comment]
I see what you've done.  You did a "git pull"  that caused your 1 commit to get the master branch merged into your branch.  

Assuming you've got "upstream" pointing at the main Xastir rep and "origin" pointing at your fork, Please do the following:
    git fetch upstream
    git checkout master
    git merge
    git checkout dialogs2
    git rebase --onto b4c555f5 32f1edb2 dialogs2

If origin is your fork and there is no upstream, please create an upstream remote so you can keep your fork properly updated.  "git remote add upstream git@github.com:Xastir/Xastir.git", then "git fetch upstream".  Then do the above.

There will be one conflict in main.c, which is easily resolved by editing src/main.c, finding the <<</===/>>> delimiters, and deleting the delimiters (the code between ==== and >>> is what should be there).  Then "git add src/main.c" and "git rebase --continue".  Your new dialogs2 branch will be correctly rebased onto the head of upstream master instead of completely whack.  

finally, git push --force your rebased branch to your fork.  If your fork is "origin" then that's "git push --force origin dialogs2".

**Comment by tvrusso** [comment]
I should also point out that "git log --decorate --graph --all --oneline" shows very clearly that your "dialogs2" branch was branched off of a very stale state, commit e9d10e62 from last June, not the most recent master, and that your fork's master is behind upstream's.

You need to fix that.  

    git checkout master
    git fetch upstream
    git merge master
    git push origin master

Do this frequently in the future to keep your fork synced with the Xastir repo, and always before doing new development you intend to push to your fork.  Always do a "git checkout master" before creating a new branch to work on, so you can be sure your new branch is not based in ancient history.

**Comment by we7u** [comment]
Did as requested. Didn't seem to change anything in this pull request. Still shows 40 commits.

**Comment by tvrusso** [comment]
The commands in this comment presumed (incorrectly) that your master branch was tracking upstream instead of origin.  I have corrected them below to remove that presumption.  The commands below will work correctly to keep your repo in sync no matter which repo your "master" checkout is tracking.

> I should also point out that "git log --decorate --graph --all --oneline" shows very clearly that your "dialogs2" branch was branched off of a very stale state, commit [e9d10e6](https://github.com/Xastir/Xastir/commit/e9d10e62595fe8b40e82c5858fd02620b793a5e1) from last June, not the most recent master, and that your fork's master is behind upstream's.
> 
> You need to fix that.
> 
> ```
> git checkout master
> git fetch upstream
> git merge upstream/master
> git push origin master
> ```
> 
> Do this frequently in the future to keep your fork synced with the Xastir repo, and always before doing new development you intend to push to your fork. Always do a "git checkout master" before creating a new branch to work on, so you can be sure your new branch is not based in ancient history.

**Comment by tvrusso** [comment]
After correctly syncing your repo with upstream using the commands above, the commands:

    git fetch upstream
    git checkout master
    git merge upstream/master
    git checkout dialogs2
    git rebase --onto b4c555f5 32f1edb2 dialogs2
     [fix conflict, git add src/main.c]
    git push --force origin dialogs2

should fix this.

**Comment by tvrusso** [comment]
OK, your fork is really borked, and its master branch is all wrong.  Probably the result of a bad git pull.  You have to fix that and then rebase.  I just did this (in a new directory where I'd cloned we7u/Xastir as origin and Xastir/origin as upstream) and it worked fine:

    git fetch upstream
    git checkout master
    git reset --hard upstream/master
    git checkout dialogs2
    git rebase --onto b4c555f5 32f1edb2 dialogs2

This forces your checkout's master branch to be exactly the same commit as upstream/master, then 
rebases your dialogs2 branch off of that.  You will still need to fix the conflict in main.c:

     [edit main.c to remove conflict markers]
     git add src/main.c
     git rebase --continue

If you now do 

   git log --decorate --graph --all --oneline

you will see a tree where dialogs2 is a simple one-commit delta off of master and upstream/master.

Now you need to fix your fork:

    git push --force origin master
    git push --force origin dialogs2

At this point, the PR should be fixed, and should contain a single commit to be merged instead of 40 new commits that redo old commits with different SHA-1s.

You can avoid this problem in the future by making sure your fork is cleanly updated and in sync with upstream before doing work in it (as shown above, and repeated here):

    git checkout master
    git fetch upstream
    git merge upstream/master
    git push origin master

This sequence should be run pretty much every time you see any work has been done by others in upstream.

**Comment by we7u** [comment]
You gave this sequence above:
```
git fetch upstream
git checkout master
git reset --hard upstream/master
git checkout dialogs2
git rebase --onto b4c555f5 32f1edb2 dialogs2
```
But looking at my local Git it looks like 32f1edb2 is a merge I did, while ffb68261 is the one I'd want to rebase onto upstream/master. Correct? I haven't performed any of the above commands yet.

**Comment by tvrusso** [comment]
On Sun, Mar 08, 2020 at 12:19:23PM -0700, we recorded a bogon-computron collision of the <notifications@github.com> flavor, containing:
> You gave this sequence above:
> ```
> git fetch upstream
> git checkout master
> git reset --hard upstream/master
> git checkout dialogs2
> git rebase --onto b4c555f5 32f1edb2 dialogs2
> ```
> But looking at my local Git it looks like 32f1edb2 is a merge I did, while ffb68261 is the one I'd want to rebase onto upstream/master. Correct? I haven't performed any of the above commands yet.

What this says is "rebase the dialogs2 branch, starting at commit 32f1edb2,
so that it branches off of b4c555f5 instead" --- which means it'll just cherry
pick commits starting at the NEXT one after 32f1edb2 onto the desired
commit.  It'll skip the merge commit you don't want.

You could accomplish the same thing by starting a new branch off of master,
then just cherry-picking the one commit into that branch.  But this way,
you have the same name for the rebased branch, and the other you'd have a 
new name.

-- 
Tom Russo    KM5VY
Tijeras, NM  

 echo "prpv_a'rfg_cnf_har_cvcr" | sed -e 's/_/ /g' | tr [a-m][n-z] [n-z][a-m]

**Comment by we7u** [comment]
I still see that pesky merge in there after those commands. Is this correct?
```
* b4285d28 (HEAD -> dialogs2) Change dialog size for dialog<screen_size
| * ffb68261 (origin/dialogs2) Change dialog size for dialog<screen_size
| *   32f1edb2 Merge remote-tracking branch 'upstream/master' into dialogs2
| |\  
| |/  
|/|   
* | b4c555f5 (upstream/master, master) Dialogs (#166)
```

**Comment by tvrusso** [comment]
On Sun, Mar 08, 2020 at 12:57:48PM -0700, we recorded a bogon-computron collision of the <notifications@github.com> flavor, containing:
> I still see that pesky merge in there after those commands. Is this correct?
> ```
> * b4285d28 (HEAD -> dialogs2) Change dialog size for dialog<screen_size
> | * ffb68261 (origin/dialogs2) Change dialog size for dialog<screen_size
> | *   32f1edb2 Merge remote-tracking branch 'upstream/master' into dialogs2
> | |\  
> | |/  
> |/|   
> * | b4c555f5 (upstream/master, master) Dialogs (#166)
> ```

Yes, but look where it is --- it's in the origin/dialogs2 branch, not the
dialogs2 (local) branch.  When you force-push dialogs2 up to origin, that 
pesky merge will be gone.

-- 
Tom Russo    KM5VY
Tijeras, NM  

 echo "prpv_a'rfg_cnf_har_cvcr" | sed -e 's/_/ /g' | tr [a-m][n-z] [n-z][a-m]

**Comment by tvrusso** [comment]
Ok, this seems cleaned up now and I can see clearly what changed, but I'm a little confused --- all it seems to have done is add a "resize_dialog" function, but I don't see anywhere where this is called.

**Comment by tvrusso** [comment]
It is possible that the reason that your master branch was messed up was that you had done some work there *before* the "merge to dialogs2" by accident, which made your master out of sync with upstream in the first place.  Then the procedure I gave above pretty much discarded that work.  

Assuming you didn't do anything crazy like delete your clone, you can recover the old (pre-rebase) dialogs2 branch very easily, because git doesn't actuall delete those commits unless you tell it to, or unless something like a month passes.  Let's recover your old dialogs2 branch and call it something else now:

    git checkout ffb6826    # This will tell you you're in "detached HEAD" state.  No problem
    git branch dialogs2_recovered    # now your new "dialogs2_recovered" branch is exactly the same as dialogs2 was before you rebased.

Now look through the history of dialogs2_recovered and look for any commits there that should have been in dialogs2 but were mistakenly on master.  Cherry pick those individual commits to dialogs2 one by one, and all should be recovered:

     git checkout dialogs2
     git cherry-pick    commit1 commit2 ...

Now diff your dialogs2 to master and make sure it's what you really want the new code to look like, and then push dialogs2 to origin (no force push needed).

**Comment by we7u** [comment]
This is another part of addressing issue #138

**Comment by tvrusso** [comment]
This is related to issue #138 .

**Pull request merged**
