### PR TITLE
Fixes build error when compiled with -fno-common or GCC-10

### PR DESCRIPTION
**Pull request by dl1jbe**
see issue #164

### CODE REVIEW

**Comment by tvrusso** [comment]
Could you please rebase your fix_fno-common branch to the latest master and then force-push it, so we can clear the false fails of the travis CI?

I'll review and commit your PR after that rebase.

**Comment by tvrusso** [comment]
Never mind my request to rebase.  I'm just going to merge this, as I have tested your fixes out locally.

**Comment by tvrusso** [comment]
Thank you for this set of fixes.

**Comment by dl1jbe** [comment]
Am Sat, 08 Feb 2020 09:40:57 -0800
schrieb Tom Russo <notifications@github.com>:

> Thank you for this set of fixes.
> 
> 

Your welcome. We stumpled about it in preparation for the coming GCC-10
release.

73, de Tom

P.S. And thanks for keeping Xastir going. 
-- 
"Do what is needful!"
Ursula LeGuin: Earthsea
--

**Pull request merged**
